version: '3.8'

services:
  postgres_db:
    container_name: postgres_integration
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  prometheus_app:
    container_name: prometheus_integration
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    restart: always

  jaeger_app:
    container_name: jaeger_integration
    image: jaegertracing/all-in-one:1.17
    ports:
      - "5775:5775/udp"
      - "5778:5778"
  grafana_app:
    container_name: grafana_integration
    image: grafana/grafana:7.0.3

    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./src:/var/lib/grafana/dashboards
volumes:
    db:
      driver: local
    prometheus_data: { }
    grafana_data: { }